version: '2'
services:
    diary-app:
        image: diary
        external_links:
            - diary-mysql:mysql
            - diary-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/diary?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    diary-mysql:
        extends:
            file: mysql.yml
            service: diary-mysql
    diary-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: diary-elasticsearch
